CC= c++
NAME=megaphone
CFLAGS= -Wall -Wextra -Werror -std=c++98
SRC= megaphone.cpp
#OBJ=$(SRC:.c=.o)


all: $(NAME)


$(NAME): $(OBJ)
	$(CC) $(CFLAGS) $(SRC) -o $(NAME)


##clean:
##	rm -rf $(OBJ)

fclean:
	rm -rf $(NAME)


re:

.PHONY: